### ISSUE TITLE
Transaction Email Templates

### ISSUE THREAD

**Issue by LinusMuema** [gotschmarcel/nodemailer-brevo-transport#2]
Hi @gotschmarcel ,
Nice job on the package. I was asking if there was a way you could include a way to enable the use of templates and passing in the variables to the templates when sending the emails.

**Comment by gotschmarcel** [comment]
Hi @LinusMuema ,

sorry for the late response. I'm currently updating the package to a more modern implementation. I'll include the template and template data API in the next release. I'll let you know as soon as I have something ready and you can give it a spin before I release it.

**Comment by LinusMuema** [comment]
That would be awesome

**Comment by alexandredemorypro** [comment]
Hi @gotschmarcel ,
Thanks for this package.
Did you do a version that include the template and template data API ?

**Comment by steve-lebleu** [comment]
Hi everyone ! It seems that the package is no longer maintened.  I don't know.  Here a fork which support dynamic templates : https://github.com/konfer-be/nodemailer-sendinblue-transport. It's not unit tested but it seems ok, except for the attachments. I don't have time to look at it now, I'll do it as soon as possible.

**Comment by gotschmarcel** [comment]
V3 support and templates were just merged to `dev` and are going to be released soon.

**Comment by gotschmarcel** [comment]
Version 2.0.0 is out with support for v3 & templates.
