### ISSUE TITLE
Add support for SIB v3 transactions API

### ISSUE THREAD

**Issue by GerkinDev** [gotschmarcel/nodemailer-brevo-transport#6]
According to https://developers.sendinblue.com/docs/migration-guide-for-api-v2-users-1#why-do-i-have-to-migrate, the V2 API might be removed since June 25th 2021

**Comment by GerkinDev** [comment]
A fork @ https://github.com/joshuachinemezu/nodemailer-sendinblue seems to support the V3 API. Maybe you might deprecate your NPM package in favor of this one, or request the owner of the fork to PR here.

**Comment by akosasante** [comment]
+1 @gotschmarcel  , I heavily use this library just wanted to check in if support for v3 is planned before the cutoff date of November 2022? https://developers.sendinblue.com/docs/apiv2-sunset-roadmap#september-november

**Comment by gotschmarcel** [comment]
I'm working on v3 support now.

**Comment by gotschmarcel** [comment]
V3 support was just merged to `dev`. Release is coming soon.

**Comment by gotschmarcel** [comment]
Version 2.0.0 is out with support for v3 & templates.
