### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by marc-on-github** [gotschmarcel/nodemailer-brevo-transport#9]
Thanks for this great project. How can I use it with typescript?

**Comment by senorprogramador** [comment]
Hi @marc-on-github , a bit late but here's how to do it:

Add a file named `sendinblue.d.ts` somewhere in your src folder and add the following:
```ts
declare module "nodemailer-sendinblue-transport/lib/transport";
```

You can then use it like this:
```ts
import Transport from "nodemailer-sendinblue-transport/lib/transport";
const transporter = nodemailer.createTransport(
  new Transport({ apiKey: process.env.SIB })
);
transporter.sendMail(mailOptions);
```

Good luck :)

**Comment by gotschmarcel** [comment]
I've added a `d.ts` file to the project so you get the constructor definition. Nodemailer has its own type definitions that you must include to get things like `sendMail` type checked.
